### ISSUE TITLE
ox db migrate command not found

### ISSUE THREAD

**Issue by danoviedo91** [wawandco/ox#16]
ox version: `v0.11.2`

I created a new buffalo project with the `ox new coke` command.
Then created a couple fizz files and tried to run them using the following command:
`ox db migrate`

But I got the following error:
`[error] subcommand migrate not found`

When running `ox help db` to check what sub commands are available, I have:

![image](https://user-images.githubusercontent.com/51673771/141509313-dd337cbb-58c3-4aa9-8d35-8f44d55f9304.png)

Based on this, there seems to be no `migrate` sub-command available.

As a side note, I'm using the globally available ox command.

**Comment by paganotoni** [comment]
This is a tricky one and may be related with #21 in the sense that now that Buffalo has buffalo.FS we could use it to replace our lovely `fsbox`. However, that would imply also changing other dependencies like Pop.

**Comment by paganotoni** [comment]
Update: I think I got it @danoviedo91, However I don't think It will be fixed for v0.12. fs.FS just makes everything veeery nice.

**Comment by paganotoni** [comment]
@danoviedo91 this one is solved in v0.12.0. LMK if you can validate it.
