### ISSUE TITLE
Jquery warns Override

### ISSUE THREAD

**Issue by jhernandez06** [wawandco/ox#2]
When creating a new project with ox it throws the following error when running:
jquery-exposed-exposed.js? ./ node_modules / expose-loader / dist / cjs.js? exposes = $, jQuery: 5 Uncaught Error: [exposes-loader] The "$" value exists in the global scope, it may not be safe to overwrite it, use the "override" option

my solution for this problem was to remove the first line from the application.js file
require ("expose-loader? exposes = $, jQuery! jquery");

**Comment by paganotoni** [comment]
This is an interesting one. It's related with updating our tooling to avoid using JQuery.
