### ISSUE TITLE
Templates and AssetsBox do not exist as render.Options

### ISSUE THREAD

**Issue by danoviedo91** [wawandco/ox#21]
When creating a new fresh app with ox, I got the following error:
![image](https://user-images.githubusercontent.com/51673771/144671373-16ab2681-a5d8-4080-963a-df40b1ab64e6.png)
Both TemplatesBox and AssetsBox do not exist as part of render.Options{} struct.

**Comment by paganotoni** [comment]
Oh! This one is interesting. This may be related with a change in Buffalo v0.18.x. It will imply some things to fix. For now, we should aim to use v0.17.x
