### ISSUE TITLE
Migration generator wrong table name

### ISSUE THREAD

**Issue by paganotoni** [wawandco/ox#37]
The migration generator seems to be generating an up migration with `create_tablename` as the name of the table. When it should be `tablename`.

p.e.
```
ox g migration create_users
```

Generates:

```
create_table("create_users") {
...
}
``` 

cc @dmuriel

**Comment by dmuriel** [comment]
@paganotoni the correct way to create a table with fizz is `create_table_tablename`. Should we also support `create_tablename` as an alternative?

**Comment by paganotoni** [comment]
I guess thats ok. but there is something weird here:


`ox generate migration create_table_userscope`

Produces
```
create_table("userscopes") {
}
```

And `ox generate migration create_userscope` produces:

```
create_table("create_userscopes") {}
```

If if `create_table` prefix is needed, then on the second case the migration should be empty. but its not. I guess thats the fix we need to implement.

**Comment by dmuriel** [comment]
Okay, that sounds right. I'll prepare a fix for that.

**Comment by paganotoni** [comment]
Thanks @dmuriel ! Appreciate it.
