### ISSUE TITLE
'ox db create' command not found

### ISSUE THREAD

**Issue by joeariasc** [wawandco/ox#4]
After to create new project and trying to create the database through the command

`ox db create`

I got the output

`[info] Using github.com/wawandco/ox/cmd/ox`
`[error] subcommand create not found`

![Screen Shot 2021-09-29 at 10 06 30 AM](https://user-images.githubusercontent.com/10789457/135296500-7cae97b6-2bcd-4113-9fe9-e1a955752384.png)

**Comment by paganotoni** [comment]
I think I figured it out. Thanks for reporting it @joeariasc

**Comment by paganotoni** [comment]
@joeariasc this one was solved in v0.10.3, thanks for reporting it.
