### ISSUE TITLE
migrator SQL generator name is affected by flags

### ISSUE THREAD

**Issue by paganotoni** [wawandco/ox#43]
In the following command invocation the name of the migration should have not been `type_sqls` it seems like the flag is being taken as the name.

```
ox generate migration --type=sql move_users_to_be_people
[info] Using cmd/ox/main.go 

[info] generated: /Users/paganotoni/code/paganotoni/agnte/migrations/20220215165209_type_sqls.up.sql
[info] generated: /Users/paganotoni/code/paganotoni/agnte/migrations/20220215165209_type_sqls.down.sql
````

cc @dmuriel

**Comment by dmuriel** [comment]
@paganotoni thanks for finding this one. I just sent PR #44, take a look when you got a chance.

**Comment by paganotoni** [comment]
This is working very well @dmuriel, Thanks!
